# Generated by Django 5.1 on 2024-08-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
